"""Parse AEMO MMSDM SQLServer DDL (create + upgrade) into structured CSVs.

Source: pre-extracted SQL files at
`reference/aemo-mmsdm-docs/_extracted/ddl/<version>/{create,alter}.sql`
(written by an earlier shell extraction step from `MMSDM_create_v*.zip` /
`MMSDM_upgrade_*.zip` archives).

DDL was generated by Sybase PowerDesigner — the structure is regular and
amenable to simple regex parsing without a full SQL parser:

  /*== Table: NAME ==*/
  create table NAME (
     COL_A  varchar(10)   not null,
     COL_B  numeric(18,8) null,
     ...
  )
  go

Renames in upgrade SQL use:

  EXEC sp_rename N'OLD_NAME', N'NEW_NAME'             -- table rename
  EXEC sp_rename N'TABLE.OLD_COL', N'NEW_COL'         -- column rename
  EXEC sp_rename N'TABLE.OLD_PK', N'NEW_PK'           -- pk/index/constraint rename

Coverage: v5.2, v5.3, v5.3_PreRelease, v5.4, v5.5, v5.6 (the 6 versions where
AEMO ships a standalone MMSDM_create / MMSDM_upgrade bundle). v5.3_PreRelease
ships only the alter SQL (the BidOffer migration kit) — its create.sql output
will be empty.

Usage:

    python scripts/extract_mmsdm_ddl.py \\
        --extracted-root reference/aemo-mmsdm-docs/_extracted/ddl \\
        --columns-out reference/MMSDM-DDL-COLUMNS.csv \\
        --renames-out reference/MMSDM-DDL-RENAMES.csv

Outputs are CSVs sorted (version, table, ordinal) for stable git diffs.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

# /*== Table: NAME ==*/  (used as section header; the actual create follows)
TABLE_HEADER_RE = re.compile(r"/\*=+\s*\*/\s*\n/\*\s*Table:\s*(\S+)\s*\*/\s*\n/\*=+\s*\*/")

# create table NAME (
#    COL  type  not null|null,
#    ...
# )
CREATE_TABLE_RE = re.compile(
    r"create\s+table\s+(\w+)\s*\(\s*(.*?)\s*\)\s*\n\s*go",
    re.IGNORECASE | re.DOTALL,
)

# Single column line — name, type-with-optional-parens, optional constraint, nullability.
# Captures e.g.:   AREAID               varchar(10)          not null,
COLUMN_LINE_RE = re.compile(
    r"^\s*(\w+)\s+([A-Za-z_]+(?:\([^)]*\))?)\s+(not\s+null|null)\s*,?\s*$",
    re.IGNORECASE,
)

# alter table NAME add constraint NAME_PK primary key (COL, COL, ...)
PK_RE = re.compile(
    r"alter\s+table\s+(\w+)\s+add\s+constraint\s+\S+\s+primary\s+key\s*\(([^)]+)\)",
    re.IGNORECASE,
)

# EXEC sp_rename [N]'OLD', [N]'NEW' [, 'SCOPE']
# - N-prefix optional (v5.3 uses N'...', v5.5 uses '...' for column renames)
# - Optional 3rd arg gives explicit scope: 'COLUMN' / 'OBJECT' / 'INDEX' / 'STATISTICS' /
#   'USERDATATYPE'. When absent, infer scope from name shape.
# - Anchored to a leading whitespace character so the match cannot occur inside a
#   single-quoted dynamic-SQL builder ( Set @cmd = 'EXEC sp_rename N''['...']'',... ),
#   where the inner sp_rename text is doubled-up quoted and never starts on its own line.
SP_RENAME_RE = re.compile(
    r"^\s*EXEC\s+sp_rename\s+N?'([^']+)'\s*,\s*N?'([^']+)'(?:\s*,\s*'([^']+)')?",
    re.IGNORECASE | re.MULTILINE,
)


def parse_create_tables(sql: str) -> list[tuple[str, list[tuple[int, str, str, bool]]]]:
    """Return list of (table_name, [(ordinal, col, type, nullable_bool), ...])."""
    out: list[tuple[str, list[tuple[int, str, str, bool]]]] = []
    for m in CREATE_TABLE_RE.finditer(sql):
        table = m.group(1)
        body = m.group(2)
        cols: list[tuple[int, str, str, bool]] = []
        for raw_line in body.splitlines():
            cm = COLUMN_LINE_RE.match(raw_line)
            if not cm:
                continue
            name, ctype, nullspec = cm.group(1), cm.group(2), cm.group(3)
            nullable = nullspec.lower().strip() == "null"
            cols.append((len(cols) + 1, name, ctype, nullable))
        if cols:  # ignore CREATE TABLE statements with no parsable columns (defensive)
            out.append((table, cols))
    return out


def parse_primary_keys(sql: str) -> dict[str, set[str]]:
    pks: dict[str, set[str]] = {}
    for m in PK_RE.finditer(sql):
        table = m.group(1)
        cols = {c.strip() for c in m.group(2).split(",") if c.strip()}
        pks.setdefault(table, set()).update(cols)
    return pks


def parse_renames(sql: str) -> list[tuple[str, str, str, str]]:
    """Return list of (scope, target_table, old, new).

    scope is one of: 'table', 'column', 'object'.
    target_table is empty for table renames.
    """
    out: list[tuple[str, str, str, str]] = []
    for m in SP_RENAME_RE.finditer(sql):
        old, new, explicit_scope = m.group(1), m.group(2), m.group(3)
        if "." in old:
            table, old_col = old.split(".", 1)
            if explicit_scope:
                # AEMO uses 'COLUMN' / 'INDEX' / 'OBJECT' / etc — collapse non-COLUMN to 'object'.
                scope = "column" if explicit_scope.upper() == "COLUMN" else "object"
            else:
                # Heuristic fallback: if old name looks like a PK/IDX/CK constraint or index
                # suffix, classify as 'object'; else as 'column'.
                obj_marker = re.search(
                    r"(_PK|_IDX|_CK|_FK|_UQ|_UK|INDEX|IDX)$", old_col, re.IGNORECASE
                )
                scope = "object" if obj_marker else "column"
            out.append((scope, table, old_col, new))
        else:
            out.append(("table", "", old, new))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--extracted-root", type=Path, required=True)
    ap.add_argument("--columns-out", type=Path, required=True)
    ap.add_argument("--renames-out", type=Path, required=True)
    args = ap.parse_args()

    if not args.extracted_root.is_dir():
        print(f"ERROR: missing {args.extracted_root}", file=sys.stderr)
        return 2

    version_dirs = sorted(p for p in args.extracted_root.iterdir() if p.is_dir())
    if not version_dirs:
        print(f"ERROR: no version dirs under {args.extracted_root}", file=sys.stderr)
        return 2

    columns_rows: list[tuple[str, str, int, str, str, int, int]] = []
    renames_rows: list[tuple[str, str, str, str, str]] = []

    for vd in version_dirs:
        version = vd.name
        create_sql_path = vd / "create.sql"
        alter_sql_path = vd / "alter.sql"

        if create_sql_path.is_file():
            sql = create_sql_path.read_text(encoding="utf-8", errors="replace")
            tables = parse_create_tables(sql)
            pks = parse_primary_keys(sql)
            for table, cols in tables:
                pk_cols = pks.get(table, set())
                for ordinal, col, ctype, nullable in cols:
                    columns_rows.append(
                        (
                            version,
                            table,
                            ordinal,
                            col,
                            ctype,
                            int(nullable),
                            int(col in pk_cols),
                        )
                    )
            print(
                f"{version:20s} create.sql -> {len(tables)} tables, "
                f"{sum(len(c) for _, c in tables)} columns",
            )
        else:
            print(f"{version:20s} create.sql -> (none)")

        if alter_sql_path.is_file():
            sql = alter_sql_path.read_text(encoding="utf-8", errors="replace")
            renames = parse_renames(sql)
            for scope, target, old, new in renames:
                renames_rows.append((version, scope, target, old, new))
            print(f"{version:20s} alter.sql  -> {len(renames)} sp_rename calls")
        else:
            print(f"{version:20s} alter.sql  -> (none)")

    # Stable sort for clean git diffs.
    columns_rows.sort()
    renames_rows.sort()

    args.columns_out.parent.mkdir(parents=True, exist_ok=True)
    with args.columns_out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["version", "table", "ordinal", "column", "type", "nullable", "is_pk"])
        w.writerows(columns_rows)
    print(f"\nWrote {len(columns_rows):,} column rows -> {args.columns_out}")

    args.renames_out.parent.mkdir(parents=True, exist_ok=True)
    with args.renames_out.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["version", "scope", "target_table", "old_name", "new_name"])
        w.writerows(renames_rows)
    print(f"Wrote {len(renames_rows):,} rename rows -> {args.renames_out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
